import theme from "../styles/theme";
import ToggleColorMode from "../components/UI/ToggleColorMode";

import { ColorModeScript } from "@chakra-ui/react";

import Head from "next/head";
import MenuScreen from "../components/Screens/MenuScreen";
import GameplayScreen from "../components/Screens/GameplayScreen";
import { useState } from "react";
import GameOverScreen from "../components/Screens/GameOverScreen";
import TestScreen from "../components/Screens/TestScreen";

export default function Home() {
  const [playGame, setPlayGame] = useState(false);
  const [gameOver, setGameOver] = useState(false);
  const [matchScore, setMatchScore] = useState(0);

  const playGameHandler = (value) => {
    setPlayGame(value);
  };

  const gameOverHandler = (value) => {
    setGameOver(value);
  };

  const matchScoreHandler = (value) => {
    setMatchScore(value);
  };

  return (
    <div>
      <Head>
        <title>Pokemon Guess</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      </header>
      <main>
        <ToggleColorMode />
        {!playGame && !gameOver && <MenuScreen onPlayGame={playGameHandler} />}
        {playGame && !gameOver && (
          <GameplayScreen
            onGameOver={gameOverHandler}
            onPlayGame={playGameHandler}
            onMatchScore={matchScoreHandler}
          />
          // <TestScreen
          //   onGameOver={gameOverHandler}
          //   onPlayGame={playGameHandler}
          //   onMatchScore={matchScoreHandler}
          // />
        )}
        {gameOver && !playGame && (
          <GameOverScreen
            onGameOver={gameOverHandler}
            onPlayGame={playGameHandler}
            matchScore={matchScore}
          />
        )}
      </main>
    </div>
  );
}
